<div class="block block-product-slider slider-list" <?php echo $slider->getRtl() ? 'dir="rtl" ' : "" ?> >
    <div class="block-title">
        <h2><?php echo $slider->getTitle() ?></h2>
    </div>
    <div class="block-content">
    <?php if (!empty($_productCollection) || !empty($_featuredCollection)): ?>
        <ul class="product-slider<?php echo $sliderId ?>">
            <?php if(!empty($_featuredCollection)): ?>
                <?php foreach ($_featuredCollection as $product): ?>
                <li class="product">
                    <div class="product-inner">
                        <div class="product-image">
                            <a href="<?php echo $product->getProductUrl() ?>"><?php echo $block->getImage($product, 'category_page_grid')->toHtml() ?></a>
                        </div>
                        <?php $product_name = $product->getName() ? $product->getName() : $product->getProductName() ?>
                        <strong class="product-name">
                            <a href="<?php echo $product->getProductUrl() ?>"><?php echo $_helper->productAttribute($product, $product_name, 'name'); ?></a>
                        </strong>
                        <?php echo $block->getProductPrice($product) ?>
                    </div>
                </li>
            <?php endforeach; ?>
            <?php endif ?>
            <?php if(!empty($_productCollection)): ?>
                <?php foreach ($_productCollection as $product): ?>
                <li class="product">
                    <div class="product-inner">
                        <div class="product-image">
                            <a href="<?php echo $product->getProductUrl() ?>"><?php echo $block->getImage($product, 'category_page_grid')->toHtml() ?></a>
                        </div>
                        <?php $product_name = $product->getName() ? $product->getName() : $product->getProductName() ?>
                        <strong class="product-name">
                            <a href="<?php echo $product->getProductUrl() ?>"><?php echo $_helper->productAttribute($product, $product_name, 'name'); ?></a>
                        </strong>
                        <?php echo $block->getProductPrice($product) ?>
                    </div>
                </li>
                <?php endforeach; ?>
            <?php endif ?>
        </ul>
    <?php endif; ?>
    </div>
</div>